backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "schedule"
    label: "開催予定一覧"
    folder: "content/schedule"
    create: true
    fields:
      - {label: "日付", name: "date", widget: "string"}
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "時間", name: "time", widget: "string", required: false}
      - {label: "場所", name: "place", widget: "string", required: false}
      - {label: "料金", name: "price", widget: "string", required: false}
      - {label: "詳細・備考", name: "body", widget: "text", required: false}

  - name: "news"
    label: "お知らせ一覧"
    folder: "content/news"
    create: true
    fields:
      - {label: "日付", name: "date", widget: "string"}
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "内容", name: "body", widget: "text", required: false}
